name: Build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 2
    - name: Create artifact
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: site
    - name: Deploy to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: site
        REMOTE_DIR: .
        # ARGS: --delete # Remove files on server that are not in the build folder
